name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      completed
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sampple-nodejs-app:latest

    - name: Push the Docker image
      run: docker push aniljos/nodejs:sample-nodejs-app
    
